#!/bin/bash

# 获取控制台指令

cmd=$*

# 判断指令是否为空
if [ ! -n "$cmd" ]
then
        echo "command can not be null !"
        exit
fi

# 获取当前登录用户
user=`whoami`

echo ""
echo "excute command \"$cmd\"："

# 在从机执行指令,这里需要根据你具体的集群情况配置，host与具体主机名一致
for host in 'hd.master' 'hd.slave1' 'hd.slave2'
do
    echo ""
    echo "===$host：================="

    ssh $user@$host $cmd
done

echo "excute successfully !"
